### ISSUE TITLE
Doesn't work well with dash-to-dock

### ISSUE THREAD

**Issue by ktosiek** [N-Yuki/gnome-shell-extension-workspace-isolated-dash#10]
When using this extension with https://extensions.gnome.org/extension/307/dash-to-dock/ the dock only get's filtered after I open the dash. Can this extension be made to apply the filtering on workspace change, not just when the dash is visible?

**Comment by N-Yuki** [comment]
Thanks for the report, but the change request is already implemented. In fact, the problem you are seeing is most likely due to the fact that Dash to Dock have added their own code for workspace isolation, so if you don't have workspace isolation in the Dash to Dock extension enabled, it tries to show all the icons.

Please try enabling workspace isolation in Dash to Dock, and disabling this extension.

**Comment by franglais125** [comment]
I didn't answer before as I wasn't sure I understood the problem (and I'm still unsure).

@ktosiek if you are using dash-to-dock from git, then yes, you can use workspace isolation from dash-to-dock's options.
If you installed from https://extensions.gnome.org/extension/307/dash-to-dock/, version 54 will be out soon (for Gnome 3.18 and up) with the workspace isolation option included.

**Comment by ktosiek** [comment]
Thank you for quick response! If dash-to-clock replaces this extension then this issue is in fact invalid, I'll see how it goes with the git version.

**Comment by ktosiek** [comment]
Looks like with the new dash-to-dock I don't need this extension. Thanks again for great support!
