### ISSUE TITLE
Show different icon for apps opened on another workspaces?

### ISSUE THREAD

**Issue by alexisLefebvre** [N-Yuki/gnome-shell-extension-workspace-isolated-dash#19]
The current version of this extension remove apps from the dash if they are running on another workspace, is it possible to keep the icon but display a different color (I have an orange bullet on Ubuntu 18.04) ?

**Comment by N-Yuki** [comment]
Hi @alexislefebvre, thanks for the question. Are you talking about non-favourited apps?

**Comment by N-Yuki** [comment]
Sorry, I accidentally sent my response part way and closed the issue.

The extension should still show your favorited apps that are open on another workspace and open a new window instead.

If you are talking about non-favorited apps, then doesn't that go against the point of this extension? What should happen when you click on the icon?

Should it open a new instance of the app? I think there was another extension that already did this? I could add an option to not filter app icons to this extension, but what is the use-case? I would like to know when and how it'll be used, so I know how to test it.
Should it switch to the other workspace with the app? That's the default behaviour of Gnome Shell.

**Comment by alexisLefebvre** [comment]
Sorry if my issue wasn't clear enough.

My use-case is: IIRC, this extension hides non-favorited apps that are running on other workspaces. My idea was to show them but show them with a different style, and keep the current behaviour that open the app from current or other workspace.

**Comment by N-Yuki** [comment]
Maybe I'm misunderstanding, but you want the default Gnome shell behaviour but with a style change to the icon when it's on another workspace?

The goal of this extension is to make each workspace work independently, and to do so, it does 3 things:
1) Overrides the list of running apps (known to the dash and app/window switcher) to just the running apps on the current workspace
2) When an app that is not open on the current workspace is activated, it opens a new instance instead of switching to the app on another workspace
3) Removes the dot style from app icons that are not running on this workspace

Your suggestion is to remove features 1+2 from this extension and maybe have a modified version of 3? At that point, I think it'll be better to just remove this extension, and have a new extension that tries to do this style change of app icons on another workspace. I could look into how feasible it is and create a new extension if it seems worthwhile.

**Comment by N-Yuki** [comment]
I looked into this. It looks possible to do, but it will be a fragile extension as it would need hard-coded styles.

The running app dot is currently created like this (https://gitlab.gnome.org/GNOME/gnome-shell/blob/master/js/ui/appDisplay.js#L1595):
```
this._dot = new St.Widget({ style_class: 'app-well-app-running-dot',
                                    layout_manager: new Clutter.BinLayout(),
                                    x_expand: true, y_expand: true,
                                    x_align: Clutter.ActorAlign.CENTER,
                                    y_align: Clutter.ActorAlign.END });
```
So the dot style is determined by your theme's 'app-well-app-running-dot' class.

What this theoretical extension would need to do is replace this._dot with a new St.Widget with a different style, but since I don't know what the style defined in 'app-well-app-running-dot' is (since it's in a separate CSS file defined in your Gnome Shell theme), I don't believe I can make a consistent looking change across all possible themes.
What is possible though is moving the position of the dot/bullet/underline though. Currently it is always centre-aligned at the bottom of the icon, but I could move it to the left or right when it's on another workspace.

So in summary:
- A full style change support would require cooperation from Gnome Shell theme creators to add support for multiple dot styles that work along with such an extension (or just implement it directly into Gnome Shell at this point)
- A crude approach would be hard-coding styles, but there's no guarantee that it'll fit or look nice in every theme
- A less powerful approach is just moving the position of the dot indicator to another point around the icon when on another workspace

Regardless, this suggestion goes against the whole point of workspace isolation, so it is not a valid feature request, and I don't believe a separate extension that moves the dot indicator for apps on another workspace would see any use, nor do I like the idea of hard-coding styles--I don't think it would be accepted onto http://extensions.gnome.org/ either.
