### ISSUE TITLE
overview slows to a crawl - 4 seconds to click on workspace

### ISSUE THREAD

**Issue by edgecase14** [N-Yuki/gnome-shell-extension-workspace-isolated-dash#5]
I have been clawing my eyes out for weeks with Ubuntu's Unity UI - I just tried Gnome3 shell, and it's close... this extension would be a dream come true for me; I would like to help debug if at all possible.  Ubuntu 15.04 Intel i915 video card.

**Comment by N-Yuki** [comment]
Thanks for reporting this. Just to confirm, this is Gnome Shell 3.14.4, correct? Does the issue occur when you only have this extension enabled and nothing else (make sure to logout/login or reboot after disabling other extensions in case another extension is not being disabled cleanly)?

**Comment by edgecase14** [comment]
On 08/17/2015 01:48 AM, N-Yuki wrote:

> Thanks for reporting this. Just to confirm, this is Gnome Shell 3.14.4,
> correct? Does the issue occur when you only have this extension enabled
> and nothing else (make sure to logout/login or reboot after disabling
> other extensions in case another extension is not being disabled cleanly)?

Yes that is the right version.  It is better after logout/login but 
there is still a noticeable pause.

## 

Coplanar Networks
http://www.coplanar.net
(519)489-4903

**Comment by N-Yuki** [comment]
I'm assuming that this is the same as bug #4 , so I will close this bug for now.
Also, I'll be focusing on 3.16+ support first, so I may not get around to 3.14 or older anymore.
Since Ubuntu 15.04 and Fedora 21 are no longer supported, this shouldn't be too bad though. I know Debian 8 still uses 3.14 and Ubuntu 14.04 still uses 3.10 though...
