### ISSUE TITLE
Icons shown for apps on different workspace

### ISSUE THREAD

**Issue by lyubenblagoev** [N-Yuki/gnome-shell-extension-workspace-isolated-dash#9]
On Gnome 3.20.2 with the extension enabled I see Icons for apps opened on another workspace. I use it along with Dash To Dock and it worked correctly. I think that I noticed this after I updated the extension to the latest version.

**Comment by N-Yuki** [comment]
Thanks for reporting this, @lyubenblagoev , however, if you are using Dash to Dock, you no longer need this extension since Dash to Dock handles isolation themselves now.
The issue you are seeing is a conflict in Dash to Dock's settings. By default, it is not set to isolate the workspace, so that extension is making the icons visible again when my extension tries to hide them.

Feel free to reopen this bug if there is an issue when Dash to Dock is not enabled.

**Comment by franglais125** [comment]
@lyubenblagoev however you will need to install it from git, since there is no update on the extensions website yet including the workspace isolation.

Here: https://github.com/micheleg/dash-to-dock/
You then only need to: `make` and `make install`.

Cheers

**Comment by lyubenblagoev** [comment]
@franglais125 I've already installed the latest Git version from the AUR (Arch Linux User Repository). 

Thank you both for the information.
